### ISSUE TITLE
Backup Directory and Backups Owned by Root

### ISSUE THREAD

**Issue by ryanknopf** [elliotmatson/Docker-Davinci-Resolve-Project-Server#125]
It looks like the backup directory, subdirectories, and backups themselves all end up being owned by root.  Is there an easy way to modify the backups docker container to use a specific user with lessor permissions (like `postgres:postgres`) for performing the backups assuming the selected backup folder has adequate permissions for that user?

**Comment by elliotmatson** [comment]
Yes, this is possible! [Here's the docs ](https://github.com/prodrigestivill/docker-postgres-backup-local)for the container that runs the backups, you would just need to add `user: postgres:postgres` to the config for the backup container, and ensure that the folder has correct permissions
