### ISSUE TITLE
Restoring backup Fails 

### ISSUE THREAD

**Issue by finnschi** [elliotmatson/Docker-Davinci-Resolve-Project-Server#126]
```
Failed to restore database: ERROR: new encoding (UTF8) 
is incompatible with the encoding of the template database 
(SQL_ASCII) HINT: Use the same encoding as in the template 
database, or use template0 as template. (22023) QPSQL: 
Unable to create query.
```

Trying to restore one of the .backup files I sadly get a error.

**Comment by elliotmatson** [comment]
@finnschi So sorry, I missed this in my notifications. Just to confirm, this is a *.backup file generated by this project, and you are restoring with the UI in Resolve? And what version of Resolve? 

I haven't been doing much editing lately, so I haven't thoroughly tested this on Resolve 19, but according to Blackmagic there were no major database server changes in 19
