### ISSUE TITLE
Support for unRAID

### ISSUE THREAD

**Issue by DesertCookie** [elliotmatson/Docker-Davinci-Resolve-Project-Server#19]
Hi, for us unRAID users it'd be awesome if you could add this to [Docker Hub](https://hub.docker.com/) so we can create an unRAID App template to install this container with one click.

**Comment by elliotmatson** [comment]
I'm not very familiar with unRAID, do you just need all the images needed by this docker-compose file available on Docker Hub?

**Comment by DesertCookie** [comment]
Yes, when available on Docker Hub, unRAID users can simply pull the image with one click and build a template with their UI that allows for other users to pull the image even easier, with all options pre-configured.

**Comment by elliotmatson** [comment]
@DesertCookie just added it in the latest release under elliotmatson/pgadmin-config-creator. If you end up making a template, would you be able to contribute some instructions to the Readme?

**Comment by DesertCookie** [comment]
I will once I get it to work.

Right now, I can't reach anything inside the container nor do not get any log output from the container.

**Comment by elliotmatson** [comment]
@DesertCookie Are you just using that one container? Right now this project uses 4 docker containers.

The one I added to Docker Hub just generates a pgadmin config and quits, so you should only see a few lines of logs from it like this
`2022-07-30T05:11:05.378136835Z created /config/servers.json
2022-07-30T05:11:05.378231723Z printing json to file...
2022-07-30T05:11:05.378250098Z {'Servers': {'1': {'Name': 'DavinciResolve', 'Group': 'Servers', 'Port': 5432, 'Username': 'postgres', 'Host': 'postgres', 'SSLMode': 'prefer', 'MaintenanceDB': 'postgres'}}}
`

**Comment by draco1544** [comment]
Thank you so much for doing this, I can't get it to work with unraid

**Comment by elliotmatson** [comment]
@draco1544 Are you using the docker compose file? I've never used unraid, so I'm not sure how it handles docker compose stacks

**Comment by draco1544** [comment]
> @draco1544 Are you using the docker compose file? I've never used unraid, so I'm not sure how it handles docker compose stacks

Yes I use the docker compose file and all containers are running, but I can't connect to the database from davinci resolve

**Comment by elliotmatson** [comment]
@draco1544 That's odd, I wonder if unraid is using that port already. Do you see any errors in the logs of any of the containers?

**Comment by DesertCookie** [comment]
unRAID only uses port 8000 for its web UI by default. If another Docker container already is using a port you are trying to assign with a new container it'll not let you - the container won't be created. That shouldn't be an issue.

At some point in the near future I'll to to get this to work but for now we're not doing much editing and this project has become more of a nice-to-have than a need-to-have.

**Comment by draco1544** [comment]
> @draco1544 That's odd, I wonder if unraid is using that port already. Do you see any errors in the logs of any of the containers?

Yes I see "root role doesn't exist" or something like that, in the postgreSQL database container

**Comment by elliotmatson** [comment]
@draco1544 Interesting. How are you deploying the docker-compose stack on unRAID? I just spun up unRAID in a VM, and then installed Portainer-CE, and used that to deploy the stack. I did see those errors, but I was able to connect to the database perfectly fine and use pgadmin4. The only thing that didn't work was pgadmin4 loading the servers file

I think the error in the logs is caused by the healthcheck command I used, I'll take a look at that, but it shouldn't impact any functionality

**Comment by draco1544** [comment]
> @draco1544 Interesting. How are you deploying the docker-compose stack on unRAID? I just spun up unRAID in a VM, and then installed Portainer-CE, and used that to deploy the stack. I did see those errors, but I was able to connect to the database perfectly fine and use pgadmin4. The only thing that didn't work was pgadmin4 loading the servers file
> 
> 
> 
> I think the error in the logs is caused by the healthcheck command I used, I'll take a look at that, but it shouldn't impact any functionality

I use the docker compose plugin available in the app catalog

**Comment by elliotmatson** [comment]
@draco1544 I just tried that one and it also seemed to work similarly, here were the logs I got:
```
resolve_pgsql                   | 
resolve_pgsql                   | PostgreSQL Database directory appears to contain a database; Skipping initialization
resolve_pgsql                   | 
resolve_pgsql                   | 2022-11-02 07:39:16.139 CDT [1] LOG:  starting PostgreSQL 13.8 (Debian 13.8-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
resolve_pgsql                   | 2022-11-02 07:39:16.139 CDT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
resolve_pgsql                   | 2022-11-02 07:39:16.139 CDT [1] LOG:  listening on IPv6 address "::", port 5432
resolve_pgsql                   | 2022-11-02 07:39:16.159 CDT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
resolve_pgsql                   | 2022-11-02 07:39:16.161 CDT [26] LOG:  database system was shut down at 2022-11-02 07:38:55 CDT
resolve_pgsql                   | 2022-11-02 07:39:16.164 CDT [1] LOG:  database system is ready to accept connections
resolve_pgadmin                 | [2022-11-02 12:39:22 +0000] [1] [INFO] Starting gunicorn 20.1.0
resolve_pgadmin                 | [2022-11-02 12:39:22 +0000] [1] [INFO] Listening at: http://[::]:80 (1)
resolve_pgadmin                 | [2022-11-02 12:39:22 +0000] [1] [INFO] Using worker: gthread
resolve_pgadmin                 | [2022-11-02 12:39:22 +0000] [86] [INFO] Booting worker with pid: 86
resolve_pgadmin                 | ::ffff:10.0.20.161 - - [02/Nov/2022:12:39:43 +0000] "GET / HTTP/1.1" 302 217 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
resolve_pgadmin                 | ::ffff:10.0.20.161 - - [02/Nov/2022:12:39:43 +0000] "GET /login?next=%2F HTTP/1.1" 200 1617 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
resolve_pgadmin                 | ::ffff:127.0.0.1 - - [02/Nov/2022:12:39:46 +0000] "GET / HTTP/1.1" 302 217 "-" "Wget"
resolve_pgadmin                 | ::ffff:127.0.0.1 - - [02/Nov/2022:12:39:46 +0000] "GET /login?next=%2F HTTP/1.1" 200 4610 "-" "Wget"
resolve_pgbackup                | 2022/11/02 07:39:16 Running version: v0.0.10
resolve_pgbackup                | 2022/11/02 07:39:16 new cron: @daily
resolve_pgbackup                | 2022/11/02 07:39:16 Opening port 8080 for health checking
```
@DesertCookie how are you deploying the stack?

**Comment by elliotmatson** [comment]
Also I fixed that error, if you make the changes in 9537f54aa392204ec7bfd9b519f49b4f963e7ef1 it should go away

**Comment by draco1544** [comment]
> @draco1544 I just tried that one and it also seemed to work similarly, here were the logs I got:
> 
> ```
> resolve_pgsql                   | 
> resolve_pgsql                   | PostgreSQL Database directory appears to contain a database; Skipping initialization
> resolve_pgsql                   | 
> resolve_pgsql                   | 2022-11-02 07:39:16.139 CDT [1] LOG:  starting PostgreSQL 13.8 (Debian 13.8-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
> resolve_pgsql                   | 2022-11-02 07:39:16.139 CDT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
> resolve_pgsql                   | 2022-11-02 07:39:16.139 CDT [1] LOG:  listening on IPv6 address "::", port 5432
> resolve_pgsql                   | 2022-11-02 07:39:16.159 CDT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
> resolve_pgsql                   | 2022-11-02 07:39:16.161 CDT [26] LOG:  database system was shut down at 2022-11-02 07:38:55 CDT
> resolve_pgsql                   | 2022-11-02 07:39:16.164 CDT [1] LOG:  database system is ready to accept connections
> resolve_pgadmin                 | [2022-11-02 12:39:22 +0000] [1] [INFO] Starting gunicorn 20.1.0
> resolve_pgadmin                 | [2022-11-02 12:39:22 +0000] [1] [INFO] Listening at: http://[::]:80 (1)
> resolve_pgadmin                 | [2022-11-02 12:39:22 +0000] [1] [INFO] Using worker: gthread
> resolve_pgadmin                 | [2022-11-02 12:39:22 +0000] [86] [INFO] Booting worker with pid: 86
> resolve_pgadmin                 | ::ffff:10.0.20.161 - - [02/Nov/2022:12:39:43 +0000] "GET / HTTP/1.1" 302 217 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
> resolve_pgadmin                 | ::ffff:10.0.20.161 - - [02/Nov/2022:12:39:43 +0000] "GET /login?next=%2F HTTP/1.1" 200 1617 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
> resolve_pgadmin                 | ::ffff:127.0.0.1 - - [02/Nov/2022:12:39:46 +0000] "GET / HTTP/1.1" 302 217 "-" "Wget"
> resolve_pgadmin                 | ::ffff:127.0.0.1 - - [02/Nov/2022:12:39:46 +0000] "GET /login?next=%2F HTTP/1.1" 200 4610 "-" "Wget"
> resolve_pgbackup                | 2022/11/02 07:39:16 Running version: v0.0.10
> resolve_pgbackup                | 2022/11/02 07:39:16 new cron: @daily
> resolve_pgbackup                | 2022/11/02 07:39:16 Opening port 8080 for health checking
> ```
> 
> @DesertCookie how are you deploying the stack?


Can i have a screenshot of your docker tab in unraid ? @elliotmatson

**Comment by draco1544** [comment]
> Also I fixed that error, if you make the changes in [9537f54](https://github.com/elliotmatson/Docker-Davinci-Resolve-Project-Server/commit/9537f54aa392204ec7bfd9b519f49b4f963e7ef1) it should go away

Thank a lot ! Its finally working ! This project is amazing

**Comment by elliotmatson** [comment]
Oh ok great! What ended up fixing it?

**Comment by draco1544** [comment]
> Oh ok great! What ended up fixing it?

Maybe the change you make in the last patch

**Comment by elliotmatson** [comment]
That's interesting, glad it's fixed! @DesertCookie Can you test as well so I can mark this closed?

**Comment by elliotmatson** [comment]
@DesertCookie What version of Resolve are you using?

**Comment by DesertCookie** [comment]
I'm using 18.0.4b5.

**Comment by draco1544** [comment]
> I've managed to set up the containers for now - I'm still unsure about the backups though and will have to wait for them to roll once. Once I have everything going I'll get you written installation instructions for unRAID (prototype [here](https://nc.rhprivat.de/s/QEzLTrtmnoJMzi5)).
> 
> 
> 
> I've been able to connect to the databse from all my devices using locally installed PgAdmin4 instances, I've not yet been able to connect resolve yet though. I always get this error: `Please check for correct credentials and if the 
> 
> server is online and allows client connections.`. Since I am able to connect from the same devices with PgAdmin the server is allowing outside connections (my home network); as credentials I'm using the same `postgres` and `DaVinci` that were set with `database` as name (for now I'm closly following your docker compose where I can).

I have used the docker compose plugin for unraid and the deployment of the stack worked for me, you should try it

**Comment by draco1544** [comment]
> Docker compose has some disadvantages for my use case. I am exposing some containers to my local network which I only know how to do with unRAID's UI, sooo... 😅. Also, the plugin causes my Docker page to load significantly longer; once I uninstalled it again it was back to fluently appearing in a split second.

Good luck to get it working 😂

**Comment by DesertCookie** [comment]
@draco1544 with what credentials exactly are you connect (name, location, username, password)?

Even with compose I can't connect via Resolve but only from pgAdmin.

**Comment by draco1544** [comment]
> @draco1544 with what credentials exactly are you connect (name, location, username, password)?
> 
> 
> 
> Even with compose I can't connect via Resolve but only from pgAdmin.

I create a database in resolve with username : postgres and password : DaVinci

**Comment by DesertCookie** [comment]
Ah, so that was the issue. I always tried to connect immediately because I was too used to just connect to the PostgreSql databases on my VMs and servers. But they all had Resolve installed too. It probably automatically initizes and sets up PostgresSql when it notices it's installed.

So, @elliotmatson, the tutorial I sent you is working and all of this could've been resolved before I even wrote here. I just never had the idea to use "create" instead of "connect" (though in fairness, other projects like [jonnyhyman/ResolveCollaboration](https://github.com/jonnyhyman/ResolveCollaboration) don't require you to use "create" and just work by immediately connecting.

Thanks for the assistance. Cheers.

**Comment by elliotmatson** [comment]
> I just never had the idea to use "create" instead of "connect" (though in fairness, other projects like [jonnyhyman/ResolveCollaboration](https://github.com/jonnyhyman/ResolveCollaboration) don't require you to use "create" and just work by immediately connecting.
> 

The reason I had it this way is so that the backups are easier to setup, but in theory create should work, just as long as you aren't using the same database name and the once created by the docker-compose stack
