### ISSUE TITLE
Resolve Project Server 18.1 Support ? 

### ISSUE THREAD

**Issue by LaBaude32** [elliotmatson/Docker-Davinci-Resolve-Project-Server#26]
Hi,

Thx for you wonderful work ! 
Is 18.1 version of project server is supported ? 

Thx !

**Comment by elliotmatson** [comment]
@LaBaude32 I haven't tested it myself, but as far as I'm aware 18 and 18.1 use the same Postgres version, so it should work

**Comment by elijahbutler** [comment]
I'm on 18.1 and I had an issue where resolve_pgsql threw error 

> initdb: error: directory "/var/lib/postgresql/data" exists but is not empty If you want to create a new database system, either remove or empty

I had to define "PGDATA" environment variable to my local path to get the database to work.

**Comment by elliotmatson** [comment]
@elijahbutler That means there were already files in the folder in ~/db, but it couldn't read them as a valid database. 

Were you updating from an older version of postgres? 

PGDATA sets the path of the database files inside of the container

**Comment by elijahbutler** [comment]
@elliotmatson I was not upgrading, this is my first time spinning up a project server. I had started the postgres server once before, but couldn't get my computer to connect, so possibly something happened there?

**Comment by elliotmatson** [comment]
Potentially! 

I would suggest clearing out that folder instead of changing PGDATA. Changing the path of the database files inside of the container means that it is no longer in the host filesystem, so if your postgres container gets deleted or updated, your database gets deleted with it

**Comment by elijahbutler** [comment]
Good to know! I’ll redeploy the stack and update if I still have problems.
