### ISSUE TITLE
Upgrade to new version possible without dataloss?

### ISSUE THREAD

**Issue by lxne** [elliotmatson/Docker-Davinci-Resolve-Project-Server#3]
Hi, I am running the previous version on a linux system. Unfortunately docker is still some kind of a black box to me.

Can I somehow upgrade to the new version (for resolve 18) without dataloss? Or will I have to import the old database somehow?

Some how-to-upgrade-instructions would be appreciated.
Thank you for this superb tool.

**Comment by elliotmatson** [comment]
In the next release I added a container for PGAdmin, which lets you backup the entire server, as well as transfer individual databases. This should make this process significantly easier
