### ISSUE TITLE
IP address issues with Resolve 18 and Docker Desktop on Windows

### ISSUE THREAD

**Issue by Steltek** [elliotmatson/Docker-Davinci-Resolve-Project-Server#31]
Just an FYI, probably nothing you can fix but maybe mention in the README: This doesn't seem to work with Resolve 18 (tested 18.1.2 Build 6) as the Postgres server/database seems to base the IP addresses of the various Resolve client hosts on what it sees... and in this case, all it sees is the Docker gateway in the 172.16... network. (There's no way to use host mode networking with Docker Desktop on Windows that I know of.)

The ClientAddr field in the Sm2SysEntryId table always has the same incorrect IP address for all stations, and thus they fail to connect to each other with "Cannot Enable Collaboration".

**Comment by elliotmatson** [comment]
@Steltek I haven't had any issues with this at all in 18, when do you see that error? On enabling multi-user?

**Comment by elliotmatson** [comment]
That's interesting, unfortunately I'm all Macs, but I might be able to spin up a few VMs to test. I just checked my database, and it doesn't seem to be storing anything in the address field, even when using collaboration

**Comment by lxne** [comment]
Hi, all Macs here, too.
Only the server is a linux mint machine.
No problems.

**Comment by Steltek** [comment]
> Hi, all Macs here, too. Only the server is a linux mint machine. No problems.

That does not match my scenario (server = Linux = you do not have the problem that Docker does not support host mode).
