### ISSUE TITLE
Best update process?

### ISSUE THREAD

**Issue by lxne** [elliotmatson/Docker-Davinci-Resolve-Project-Server#33]
Hi Elliot,

is the best update process still like:

1.     Save a database backup (or use one from the backup container)
2.     Destroy the old docker-compose stack
3.     Run the new docker-compose stack
4.     Import the backup in Resolve

What can the PGAdmin Container contribute to the update process and how?
I know how to use PGAdmin but not in this context.
Could you explain it in a view lines, or do you know of a link that could clear things out for me?

Best wishes,
Alex

**Comment by elliotmatson** [comment]
Sorry I should have been clearer in the release notes, that process is only needed for major version updates that change the postgres version (like from v17.x.x to v18.x.x). The last release just made a few security/dependency updates to my Docker container, so you should be able to just re-pull that image.

As far as PGAdmin, I really haven't used it in any advanced capacity, it was just requested by people enough that it seemed worth adding. I might be able to take a look at it in the near future though!
