### ISSUE TITLE
No Declaration was found

### ISSUE THREAD

**Issue by OnewheelerSA** [elliotmatson/Docker-Davinci-Resolve-Project-Server#43]
This problem is defiantly my side I'm sure but I can't figure out what's wrong here. Any ideas how I fix this?

The Compose YAML is invalid
Named volume "share/Davinci
Resolve/DB:/var/lib/postqresql/data:rw" is used in service "postgres" but no declaration was found in the volumes section.

**Comment by elliotmatson** [comment]
It looks like Docker is interpreting that string as a volume, rather than a bind-mount. Try switching it to "/share/Davinci
Resolve/DB...", it might need that initial slash to know that we are bind-mounting

**Comment by OnewheelerSA** [comment]
Legend, that worked! Thanks so much. 

Next issue now, Sorry. 

Background task error for application_custom Resolve: ERROR: for resolve_pgadmin Cannot start service pgadmin: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/entrypoint.sh": stat /entrypoint.sh: permission denied: unknown ERROR: for pgadmin Cannot start service pgadmin: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/entrypoint.sh": stat /entrypoint.sh: permission denied: unknown Encountered errors while bringing up the project.

**Comment by elliotmatson** [comment]
That's a new one, what are you running this on?

**Comment by OnewheelerSA** [comment]
Running on a QNAP

**Comment by OnewheelerSA** [comment]
Not sure if it has anything to do with it but it also wont start the Postgres container.

**Comment by elliotmatson** [comment]
With the same error?

**Comment by OnewheelerSA** [comment]
Well it doesn't actually give me an error for why it wont run the Postgres container. It just doesn't start it. Not sure if there is a way of getting a log for this or not?

**Comment by elliotmatson** [comment]
Yea, you should be able to just click on that container in Container station and it will show logs

**Comment by OnewheelerSA** [comment]
Any ideas on this issue? Tried removing everything and starting from the beginning. Same issue.

**Comment by OnewheelerSA** [comment]
Background task error for application_custom Resolve: ERROR: for resolve_pgadmin Cannot start service pgadmin: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/entrypoint.sh": stat /entrypoint.sh: permission denied: unknown ERROR: for pgadmin Cannot start service pgadmin: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/entrypoint.sh": stat /entrypoint.sh: permission denied: unknown Encountered errors while bringing up the project.

**Comment by elliotmatson** [comment]
Maybe try deleting the pgadmin section to run it without PGAdmin? I haven't seen that error before, it looks like the container doesn't have permissions to execute the entrypoint command in the container, but there isn't really anything we can do to change that.

**Comment by elliotmatson** [comment]
@OnewheelerSA were you able to test this any further?

**Comment by OnewheelerSA** [comment]
I tried but wasn't able to get it to work. Not sure if the issue is with my Qnap possibly.

**Comment by OnewheelerSA** [comment]
I see above you said to update QTS/Container Station. I didn't try that either. I will need to check updates and run them all at a convenient time.
