### ISSUE TITLE
Help: Is there any way to recover the postgreSQL database in case of docker compose down ?

### ISSUE THREAD

**Issue by Akronix** [elliotmatson/Docker-Davinci-Resolve-Project-Server#60]
Hello.

I think I did a mistake. I wanted to change the database being backed by this docker compose by modifying the [POSTGRES_DB variable](https://github.com/elliotmatson/Docker-Davinci-Resolve-Project-Server/blob/main/docker-compose.yml#L5). I replaced the name of `database` by another one that is being used inside Davinci, let's call it `cinema`. I did a `docker compose down` and a `docker compose up` and the service stopped working. I went to the docker-compose.yml and change back `cinema` by `database` and still the service doesn't work. What is going on? Is it still possible to recover the functionality or the content of the `cinema` database?

**Comment by elliotmatson** [comment]
> I replaced the name of database by another one that is being used inside Davinci, let's call it cinema

Did the `cinema` database already exist on this Postgres server? Or Just in Resolve?

Can you add docker logs of the postgres container?

**Comment by Akronix** [comment]
Ju

> > I replaced the name of database by another one that is being used inside Davinci, let's call it cinema
> 
> Did the `cinema` database already exist on this Postgres server? Or Just in Resolve?

cinema database was created through the Davinci Resolve application but in the "server" mode (by adding a new library of projects), so it should have been allocated in the postgreSQL server instance, but not in the default database. Well, that is if my assumption is correct: Davinci "Library of projects" map to a postgreSQL database, am I right?

> Can you add docker logs of the postgres container?

Hold on..

**Comment by Akronix** [comment]
> 
> Can you add docker logs of the postgres container?

Here you go:
```

PostgreSQL Database directory appears to contain a database; Skipping initialization

2023-04-25 16:50:48.072 CEST [1] LOG:  starting PostgreSQL 13.10 (Debian 13.10-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2023-04-25 16:50:48.073 CEST [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-04-25 16:50:48.073 CEST [1] LOG:  listening on IPv6 address "::", port 5432
2023-04-25 16:50:48.152 CEST [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-04-25 16:50:48.159 CEST [27] LOG:  database system was shut down at 2023-04-25 16:50:40 CEST
2023-04-25 16:50:48.170 CEST [1] LOG:  database system is ready to accept connections
2023-04-25 16:52:46.388 CEST [1] LOG:  received fast shutdown request
2023-04-25 16:52:46.390 CEST [1] LOG:  aborting any active transactions
2023-04-25 16:52:46.392 CEST [1] LOG:  background worker "logical replication launcher" (PID 33) exited with exit code 1
2023-04-25 16:52:46.392 CEST [28] LOG:  shutting down
2023-04-25 16:52:46.414 CEST [1] LOG:  database system is shut down

PostgreSQL Database directory appears to contain a database; Skipping initialization

2023-04-25 16:52:54.656 CEST [1] LOG:  starting PostgreSQL 13.10 (Debian 13.10-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2023-04-25 16:52:54.657 CEST [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-04-25 16:52:54.657 CEST [1] LOG:  listening on IPv6 address "::", port 5432
2023-04-25 16:52:54.681 CEST [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-04-25 16:52:54.688 CEST [28] LOG:  database system was shut down at 2023-04-25 16:52:46 CEST
2023-04-25 16:52:54.698 CEST [1] LOG:  database system is ready to accept connections
```

Firstly, I could acesss to ``database`` by doing `docker exec -ti database psql -U postgres`, using the command `\c database` and I could see the tables inside, although I could not connect to it with DaVinci or with pgadmin (was returning "Connection refused" for some reason I can't understand). I was playing with UNIX permissions in order to try to fix that connection issue, and now if I enter again with psql inside the docker,  I see an empty database with no tables.
Still, I can see the `db` directory with most of the files not modified.

**Comment by elliotmatson** [comment]
Did the stack create any backups before you made changes to `POSTGRES_DB`?

It seems like there might be a mix of permissions issues and database corruption here, and I'm not really certain how much can be recovered

**Comment by Akronix** [comment]
The backups created are only for the  `database`, but not for `cinema` (This is what I wanted to change).

I think so too. But I am surprised the docker volume definition for the postgreSQL instance does not persistent the data for all databases, independently of the one that's been used by default or backed up.

Maybe it would be a good idea to back up all databases since DaVinci allows to create project libraries willy-nilly? I think this can be using `POSTGRES_CLUSTER=TRUE` in the `docker-postgres-backup-local` container. Just a suggestion, but this should be tested prior to change the code of the repo, of course.

Thank you anyway for your help :)

**Comment by elliotmatson** [comment]
> Maybe it would be a good idea to back up all databases since DaVinci allows to create project libraries willy-nilly? I think this can be using `POSTGRES_CLUSTER=TRUE` in the `docker-postgres-backup-local` container. Just a suggestion, but this should be tested prior to change the code of the repo, of course.

It's been a bit since I looked at this, but if I remember correctly the reason I chose not to do this is to keep the backup files compatible with the ones created by Resolve itself. I think at the time, the cluster backups used a different format. I can look at that again soon though!

**Comment by Akronix** [comment]
Thank you @elliotmatson ! If you could look at it, that'd be great!

**Comment by Akronix** [comment]
Hello again.

Just coming back to say that I was unable to recover that data, somehow the database got corrupted, removed or overwritten, even though I don't remember to have removed any volume or anything apart from changing the POSTGRES_DB variable.

I'm closing this issue, but before I just want to highly advise to do a database backup before any change to the docker configuration.

PD: I did some small improvements to the docker-compose.yml file: persistence for the config of pgadmin and making accessible the database backups in pgadmin for easier restoring. I can do a PR to add this improvements if you want.

**Comment by elliotmatson** [comment]
> PD: I did some small improvements to the docker-compose.yml file: persistence for the config of pgadmin and making accessible the database backups in pgadmin for easier restoring. I can do a PR to add this improvements if you want.

Those all sound helpful! Definitely submit a PR if you have time!
