### ISSUE TITLE
pgbackups Can't pulling it off

### ISSUE THREAD

**Issue by qq527364584** [elliotmatson/Docker-Davinci-Resolve-Project-Server#99]
[docker-compose.txt](https://github.com/elliotmatson/Docker-Davinci-Resolve-Project-Server/files/12512927/docker-compose.txt)
Hello, I would like to deploy da Vinci automatic backup on Synology. When executing this file via windteam, execute to Pulling pgbackups (prodrigestivill/postgres-backup-local:13)... I can't pull it down, and it says "ERROR: error pulling image configuration: read tcp 192.168.99.99:55340->104.16.101.207:443: read: connection reset by peer". My side is in China. Looking forward to replying, thank you.

**Comment by elliotmatson** [comment]
That's odd, it seems like it's having trouble connecting to the docker container repo. Since that image isn't mine, I can't upload it to ghcr.io, but maybe try pulling that image on another computer? Something like:
`docker pull prodrigestivill/postgres-backup-local:13`
